"""remove_user_account_relationship

Revision ID: 7d6b0516279b
Revises: f9bcba317aa5
Create Date: 2025-04-11 22:15:33.365973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d6b0516279b'
down_revision = 'f9bcba317aa5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 