"""update_account_model

Revision ID: 7ef999e2f595
Revises: b9d7a336219d
Create Date: 2025-04-11 22:14:07.991924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ef999e2f595'
down_revision = 'b9d7a336219d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('title', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('seller', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_accounts_title'), 'accounts', ['title'], unique=False)
    op.drop_constraint('accounts_user_id_fkey', 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('accounts_user_id_fkey', 'accounts', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_accounts_title'), table_name='accounts')
    op.drop_column('accounts', 'seller')
    op.drop_column('accounts', 'image_url')
    op.drop_column('accounts', 'title')
    # ### end Alembic commands ### 