"""remove_user_account_relationship

Revision ID: f9bcba317aa5
Revises: 7ef999e2f595
Create Date: 2025-04-11 22:15:18.374299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9bcba317aa5'
down_revision = '7ef999e2f595'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 